// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbN4awHvNUZWC-uCgU_hR7iYiHk-3dpv8',
    appId: '1:573038013067:web:44b96286178e69217a828e',
    messagingSenderId: '573038013067',
    projectId: 'learnaria-483e7',
    authDomain: 'learnaria-483e7.firebaseapp.com',
    storageBucket: 'learnaria-483e7.firebasestorage.app',
    measurementId: 'G-NFR5LY716K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbxhrgXcvrUKFcqjCIdkPMmNYigvCuqNk',
    appId: '1:573038013067:android:db33a27f5739146a7a828e',
    messagingSenderId: '573038013067',
    projectId: 'learnaria-483e7',
    storageBucket: 'learnaria-483e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbPif3TL_75uQkG7x_UlTWvcrPMcTe9g8',
    appId: '1:573038013067:ios:38d4df946cf79a287a828e',
    messagingSenderId: '573038013067',
    projectId: 'learnaria-483e7',
    storageBucket: 'learnaria-483e7.firebasestorage.app',
    iosBundleId: 'com.example.learnaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbPif3TL_75uQkG7x_UlTWvcrPMcTe9g8',
    appId: '1:573038013067:ios:38d4df946cf79a287a828e',
    messagingSenderId: '573038013067',
    projectId: 'learnaria-483e7',
    storageBucket: 'learnaria-483e7.firebasestorage.app',
    iosBundleId: 'com.example.learnaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbN4awHvNUZWC-uCgU_hR7iYiHk-3dpv8',
    appId: '1:573038013067:web:7ac238c0d64dfc557a828e',
    messagingSenderId: '573038013067',
    projectId: 'learnaria-483e7',
    authDomain: 'learnaria-483e7.firebaseapp.com',
    storageBucket: 'learnaria-483e7.firebasestorage.app',
    measurementId: 'G-LEPJ29F02R',
  );
}
