import 'package:flutter/material.dart';
import 'package:learnaria/screens/splash.dart';
import 'package:learnaria/utils/app_styles.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'package:learnaria/firebase_options.dart'; // Generated by FlutterFire CLI
import 'package:firebase_auth/firebase_auth.dart'; // NEW: Import Firebase Auth

// Import Firestore API service to initialize it
import 'package:learnaria/screens/main_layout.dart'; // NEW: Import MainLayoutScreen

void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Ensure Flutter widgets are initialized
  await Firebase.initializeApp( // NEW: Initialize Firebase here directly
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // FirestoreApi.initializeFirebase(); // OLD: No longer needed here, Firebase is initialized above
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Learnaria',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: AppColors.primaryYello,
        hintColor: AppColors.mediumGrey,
        fontFamily: 'Inter',
        scaffoldBackgroundColor: Colors.white,
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          elevation: 0,
          scrolledUnderElevation: 0,
          surfaceTintColor: Colors.transparent,
          iconTheme: IconThemeData(color: AppColors.primaryBlack),
          titleTextStyle: TextStyle(
            color: AppColors.primaryBlack,
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: primaryButtonStyle(),
        ),
        textButtonTheme: TextButtonThemeData(
          style: TextButton.styleFrom(
            foregroundColor: AppColors.primaryYello,
          ),
        ),
        checkboxTheme: CheckboxThemeData(
          fillColor: MaterialStateProperty.resolveWith((states) {
            if (states.contains(MaterialState.selected)) {
              return AppColors.primaryYello;
            }
            return AppColors.mediumGrey;
          }),
        ),
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: AppColors.lightGrey,
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10.0),
            borderSide: BorderSide.none,
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10.0),
            borderSide: BorderSide.none,
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10.0),
            borderSide: BorderSide(color: AppColors.primaryYello, width: 1.5),
          ),
          hintStyle: AppTextStyles.secondaryText,
          contentPadding: const EdgeInsets.symmetric(vertical: 16.0, horizontal: 16.0),
        ),
      ),
      // NEW: Use StreamBuilder to check authentication state
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const SplashScreen(); // Show splash screen while checking auth state
          }
          if (snapshot.hasData) {
            // User is logged in, navigate to MainLayoutScreen
            return const MainLayoutScreen(); 
          } else {
            // User is not logged in, navigate to IntroScreen
            return const SplashScreen();
          }
        },
      ),
    );
  }
}
